#!/usr/bin/env ruby

project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
$LOAD_PATH.unshift File.join(project_dir, 'lib')

require 'tunnelss'

# prevent STDOUT & STDERR to be reopened (apps do this to be able to log under Passenger)
def STDOUT.reopen(*args); end
def STDERR.reopen(*args); end

begin
  require "pry"
  Interpreter = Pry
rescue LoadError
  require "irb"
  require "irb/completion"
  Interpreter = IRB
end

# START
Interpreter.start
