#!/usr/bin/env ruby

project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
$LOAD_PATH.unshift File.join(project_dir, 'lib')

require 'tunnelss'

unless ARGV.size == 0 || ARGV.size == 2
  puts <<-D
Usage:
    tunnelss [from to]

Examples:
    tunnelss 443 3000
    tunnelss localhost:443 localhost:3000

  D
  exit!
end

Tunnelss.run!(*ARGV)
